NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
library(dplyr)
library(ggplot2)
d <- filter(NEI, fips == "24510")
d <- mutate(group_by(d, type, year), s = sum(Emissions))
png(filename = "plot3.png")
print(qplot(year, s, data = d, color = type, geom = "line"))
dev.off()